url: https://cele-carrillo.github.io
baseurl: ""

# Default language
lang: es

languages:
  es: Español
  en: English

# Site settings
title: Yogestalt
email: ady.yoga@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# translations
t:
  en:
    misc:
      close: Close
    intro:
      lead_in: "Clear the mind, tone the body, open to inspiration"
      title: "A practice towards integration"
      btn_more: Tell Me More
    yogestalt:
      menu: Yogestalt
      title: "What is Yogestalt?"
      subtitle: "To trust in our own organic nature."
      contact_link: "Join<br>a class<br>today!"
    team:
      menu: About Us
      title: Our amazing team
      subtitle: "Yogestalt, a practice towards integration"
      footer: "En la práctica las personas reciben elementos para hacerse cargo de su bienestar de forma independiente y por propia motivación. Esto da como resultado satisfacción interior, tranquilidad, vitalidad e interacción social."
      footer: "When practicing, people receive elements that allow them to take ownership of their well-being, in an autonomus way and by self-motivation. This results in inner satisfaction, tranquility, vibrancy, and social interaction"
    practice:
      menu: Practice
      title: The practice
      subtitle: The ways in which we practice and what they mean to us
    timeline:
      traditional_practices:
        title: Traditional practices
        text: "In Yogestalt the integration of traditional practices such as ásanas (body positions), pránáyámas (expansion of energy through breathing), mantras (vocalization), mudrás (gestures made with the hands), yoganidra (integration through sleep), dhyána (concentration, contemplation), kriyás (organic activation) provide practical resources for daily life which can be used at any time."
      intention:
        title: Our intention
        text: "In Yogestalt there is a permanent intention to withdraw from the preconceived ideas in order to begin a journey of self-discovery, becoming aware of the opposing aspects that make us who we are and which give rise to the turmoil of our  consciousness. Yogestalt proposes various ways of practicing so as to identify these opposites, as well as the tension between. Once this tension becomes obvious, how to respond to it appears organically. This organic response would be similar to when it itches and we scratch, or when we feel thirsty and drink water, so as to satisfy our need in a spontaneous and not speculative manner."
      practice:
        title: The practice
        text: "In this practice, people learn to take care of their own wellbeing, with autonomy and self-motivation,  which brings a sense of satisfaction, tranquility, vitality and social interaction. People also develop a stronger self-esteem, and the ability to solve difficulties in managing internal and external pressure and physical and emotional stress."
      learnings:
        title: What we learn
        text: "By practicing we learn to contact our own polarities: the left side and the right side, what is accepted and what is rejected; we learn to discover where we feel tension and where relaxation, where we are open and where closed. We also learn to get in touch with emotions such as joy and sorrow, cruelty and compassion, aggression and submission, love and fear. As well as with many other opposing aspects we discover through experience."
      present:
        title: Being present
        text: "From the practice of being fully present, states of deep concentration and awareness arise. This brings about a break in the flow of thoughts which results in an accurate and authentic doing and being. In this state, we can rediscover the movement and shape of our own feelings and thoughts, as well as those emerging from the encounter with others, relearning to communicate the needs that originate from this interaction. You learn to be present in the here and now, to connect with your own polarities, sensations, feelings, thoughts, intuition, with the superficial and deep aspects of yourself, with what is being done, how it’s being done, what is being felt, and what needs surface."
    angas:
      asana:
        title: Ásana
        subtitle: "To find a position, feel and contemplate yourself in it, and do as you need."
        description: "Discovering one's position trying to remain present, feeling, with the intention of reaching a state of deep comfort. Through the position of the body a trip to the energetic, emotional, mental, intuitive, superficial and deep aspects emerges."
      mudra:
        title: Mudrá
        subtitle: "Gestures made with our hands."
        description: "The gestures made with our hands set in motion superficial and deep experiences. The gestures change the states of consciousness."
      pranayama:
        title: Pránáyáma
        subtitle: "To expand and contract ourselves through breathing."
        description: "Breathing in various ways energy expands."
      kriya:
        title: Kriyá
        subtitle: "Organic activation."
        description: "Organic activation by means of water, air and heat."
      mantra:
        title: Mantra
        subtitle: "Sound as instrument for the mind."
        description: "Sound vibration and its effects on the internal and external aspects."
      yoganidra:
        title: Yoganidra
        subtitle: "The time to integrate dreaming with being awake."
        description: "By lying in a contemplative manner, we experience the state that arises between sleep and wakefulness."   
      puja:
        title: Pújá
        subtitle: "Appreciating, offering and giving."
        description: "The time to connect with giving and appreciating."
      dhyana:
        title: Dhyana
        subtitle: "Contemplation."
        description: "Regaining the contemplative state that brings us to the present, stimulating our awareness."
    people:
      entry_ricardo: Buenos Aires - Argentina
      entry_cristina: Santa Cruz - Argentina
      entry_celeste: Sydney - Australia
    contact:
      menu: Contact
      title: Contact Us
      subtitle: "Welcoming the chance to practice in different places around the world, be it face to face o via videoconference. Meeting like-minded who embrace the ideas behind Yogestalt."
      name: Your Name *
      email: Your Email *
      phone: Your Phone
      message: Your message *
      submit: Send Message
      subject: Question from website
      require_name: Please enter your name.
      require_email: Please enter your email address.
      require_message: Please enter a message.
      submit_ok: Your message has been sent.
      submit_fail: "Your message could not be sent, try again later or send us an email to <a href='mailto:ady.yoga@gmail.com'>ady.yoga@gmail.com</a>."
  es:
    misc:
      close: Cerrar
    intro:
      lead_in: "Despejar la mente, tonificar el cuerpo, abrir a la inspiración"
      title: "Una práctica hacia la integración"
      btn_more: Leer más
    yogestalt:
      menu: Yogestalt
      title: "¿Qué es Yogestalt?"
      subtitle: "Confiar en la propia naturaleza orgánica."
      contact_link: "Sumate<br>a la<br>práctica!"
    team:
      menu: Nosotros
      title: Nuestro gran equipo
      subtitle: "Yogestalt, una práctica hacia la integración"
      footer: "En la práctica las personas reciben elementos para hacerse cargo de su bienestar de forma independiente y por propia motivación. Esto da como resultado satisfacción interior, tranquilidad, vitalidad e interacción social."
    practice:
      menu: Práctica
      title: La práctica
      subtitle: Nuestras formas de practicar y qué significan para nosotros
    timeline:
      traditional_practices:
        title: Prácticas tradicionales
        text: "En Yogestalt la integración de prácticas tradicionales como ásanas (posiciones corporales), pránáyámas (expansión de la energía por medio de la respiración), mantras (vocalización), mudrás (gestos hechos con las manos), yoganidrá (la integración a través del sueño), dhyána (concentración, contemplación), kriyás (activación orgánica) proporcionan recursos prácticos para la vida cotidiana que se pueden hacer en cualquier momento."
      intention:
        title: Nuestra intención
        text: "En Yogestalt hay una permanente intención de retirarse de las ideas preconcebidas para iniciar un camino personal de descubrimiento consciente de las partes opuestas que nos conforman y dan origen a los torbellinos de la conciencia. Yogestalt propone diversas prácticas para facilitar el reconocimiento de dichos opuestos, la tensión que existe entre ellos y profundizar en el contacto. Una vez reconocida dicha tensión,  surge la forma de responder orgánicamente. Esta respuesta orgánica sería similar a cuando sentimos picazón y nos rascamos, o cuando sentimos sed y bebemos agua para satisfacer de forma espontánea, no especulativa, esta necesidad."
      practice:
        title: La práctica
        text: "En la práctica las personas aprenden a hacerse cargo de su bienestar de forma independiente y por propia motivación, de lo que surge una sensación de satisfacción, tranquilidad, vitalidad e interacción social. Se desarrolla un fortalecimiento en la autoestima, en la capacidad para resolver dificultades, en la gestión de la presión interna y externa, y en la administración del estrés físico y emocional."
      learnings:
        title: Lo que aprendemos
        text: "Al practicar se aprende a entrar en contacto con las polaridades. Con el lado izquierdo y el lado derecho, con lo que se acepta y lo que se rechaza. Se aprende a descubrir dónde se siente la tensión corporal y dónde la distensión, dónde abierto y dónde cerrado. A entrar en contacto con emociones como la agresión y la sumisión, la alegría y la tristeza, la crueldad y la compasión, el amor y el miedo. Otros opuestos se descubrirán por medio de la experiencia."
      present:
        title: Estando presentes
        text: "Al estar presente se vivencian estados de profunda concentración y el “darse cuenta” (awareness), en el que surge un descanso en el flujo de los pensamientos que da lugar a un hacer preciso y auténtico en el que se descubre el movimiento y forma de los propios sentimientos y pensamientos. Como aquellos momentos que surgen en el encuentro con otras personas en los que se reaprende a comunicar las necesidades según lo que se manifiesta en la interacción. Se aprende a estar en el aquí y ahora, a conectarse con las polaridades, con las sensaciones, con los sentimientos, con los pensamientos, con la intuición, con los aspectos superficiales y profundos de sí mismo, con lo que se hace, con el cómo se hace, con el dónde se hace, con lo que se siente al hacer lo que se hace, con lo que se necesita y con el hacer lo que se necesita."
    angas:
      asana:
        title: Ásana
        subtitle: Ubicarse, sentirse, contemplarse y  hacer lo que se necesita.
        description: "Descubrir la propia posición intentando permanecer presente, sintiéndose y con la intención de llegar a una profunda comodidad. Por medio de la posición se propone un viaje de lo corporal a lo energético, a lo emocional, a lo mental, a lo intuitivo, hacia los aspectos superficiales y profundos."
      mudra:
        title: Mudrá
        subtitle: Los gestos hechos con las manos. 
        description: "Gestos hechos con las manos que abren a experiencias superficiales y profundas, y modifican los estados de conciencia."
      pranayama:
        title: Pránáyáma
        subtitle: Expandirse y contraerse por medio del respirar.
        description: "Respirando de diversas maneras la energía se expande."
      kriya:
        title: Kriyá
        subtitle: Activación orgánica.
        description: "Activación orgánica por medio del agua, del aire y del calor."
      mantra:
        title: Mantra
        subtitle: "El sonido, instrumento para la mente."
        description: "La vibración del sonido y sus efectos sobre lo interno y externo."
      yoganidra:
        title: Yoganidra
        subtitle: El momento de integrar lo onírico con la vigilia.
        description: "Al permanecer de manera contemplativa se experimenta ese estado que está entre el estar dormido y el estar despierto."
      puja:
        title: Pújá
        subtitle: Ofrendarse y ofrendar.
        description: "El momento de conectarse con el darse y con el dar."
      dhyana:
        title: Dhyana
        subtitle: Contemplación.
        description: "Recuperar el estado contemplativo nos ayuda a estar cuidadosamente presentes para dar lugar al “darse cuenta”(awareness)."
    people:
      entry_ricardo: Buenos Aires - Argentina
      entry_cristina: Santa Cruz - Argentina
      entry_celeste: Sydney - Australia
    contact:
      menu: Contacto
      title: Contactanos
      subtitle:
        - "Haciendo posible practicar en diversos lugares del mundo, personalmente o por videoconferencia."
        - "Encontrándonos con personas identificadas con la propuesta de Yogestalt."
      name: Tu Nombre *
      email: Tu Email *
      phone: Tu Teléfono
      message: Tu Mensaje *
      submit: Enviar
      subject: Consulta desde la página
      require_name: Por favor ingresá tu nombre.
      require_email: Por favor ingresá tu dirección de email.
      require_message: Por favor ingresá tu mensaje.
      submit_ok: Tu mensaje fue enviado.
      submit_fail: "No se pudo enviar tu consulta, intentá nuevamente o escribinos a <a href='mailto:ady.yoga@gmail.com'>ady.yoga@gmail.com</a>."

timeline:
- item: traditional_practices
  img: 1.jpg
- item: intention
  img: 2.jpg
- item: practice
  img: 3.jpg
- item: learnings
  img: 4.jpg
- item: present
  img: 5.jpg

angas:
- item: asana
  modal-id: 1
  img: asana.jpg
  thumbnail: asana-thumbnail.jpg

- item: mudra
  modal-id: 2
  img: mudra.jpg
  thumbnail: mudra-thumbnail.jpg

- item: pranayama
  modal-id: 3
  img: pranayama.jpg
  thumbnail: pranayama-thumbnail.jpg

- item: kriya
  modal-id: 4
  img: kriya.jpg
  thumbnail: kriya-thumbnail.jpg

- item: mantra
  modal-id: 5
  img: mantra.jpg
  thumbnail: mantra-thumbnail.jpg

- item: yoganidra
  modal-id: 6
  img: yoganidra.jpg
  thumbnail: yoganidra-thumbnail.jpg

- item: puja
  modal-id: 7
  img: puja.jpg
  thumbnail: puja-thumbnail.jpg

- item: dhyana
  modal-id: 8
  img: dhyana.jpg
  thumbnail: dhyana-thumbnail.jpg

# Team names, titles and social links
people:
- name: Ricardo Risso Patrón
  pic: ricardo
  description: entry_ricardo
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Cristina Di Salvo
  pic: cristina
  description: entry_cristina
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Celeste Carrillo
  pic: cele
  description: entry_celeste
  social:
    - title: info
      url: http://www.omshankara.com/
    - title: envelope
      url: mailto:info@omshankara.com


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty